package View;


import Utils.ClienteDTO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Utils.FuncionarioDTO;
import Utils.HttpConnection;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Oruam
 */
public class Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFuncionarios
     */
    private void carregarClientes() {
        // Instância a classe de conexão
        HttpConnection httpConnection = new HttpConnection();

        // Chama o método para listar os funcionários cadastrados
        List<ClienteDTO> clientes = httpConnection.listarClientes();

        // Obtem o modelo da tabela
        DefaultTableModel Tabela = (DefaultTableModel) jTClientes.getModel();

        // Limpa a tabela antes de adicionar os novos dados
        Tabela.setRowCount(0);

        // Itera sobre a lista de funcionários e adiciona os dados na tabela
        for (ClienteDTO cliente : clientes) {
            Object[] dados = {
                cliente.getNome(), 
                cliente.getCpf_Cliente(), 
                cliente.getData_nascimento(), 
                cliente.getTelefone_Cliente(), 
                cliente.getGeneroCliente(),
                cliente.getEmail(),
                cliente.getIdCliente()
            };
            Tabela.addRow(dados);
        }
    }
    
    public Clientes() {
        initComponents();
        carregarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Limpar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTTelefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        JBRemover = new javax.swing.JButton();
        jTEmail = new javax.swing.JTextField();
        JBAtualizar = new javax.swing.JButton();
        JBAdicionar = new javax.swing.JButton();
        jCGenero = new javax.swing.JComboBox<>();
        jTNome = new javax.swing.JTextField();
        jTConfirmarSenha = new javax.swing.JPasswordField();
        jTSenha = new javax.swing.JPasswordField();
        jTCpf = new javax.swing.JFormattedTextField();
        jTDataNascimento = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jButton6.setText("jButton6");

        Limpar.setText("jMenuItem1");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Limpar);

        setBorder(null);
        setTitle("Funcionários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setInheritsPopupMenu(true);
        setName("Tela Funcionário"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTClientes.setBackground(new java.awt.Color(51, 51, 51));
        jTClientes.setForeground(new java.awt.Color(255, 255, 255));
        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cpf", "Data de nascimento", "Telefone", "Gênero", "E-mail", "Código"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientes);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTTelefone.setBackground(new java.awt.Color(51, 51, 51));
        jTTelefone.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefone:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTTelefone.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jTTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTTelefone.setToolTipText("");
        jPanel3.add(jTTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gênero:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        JBRemover.setBackground(new java.awt.Color(255, 0, 0));
        JBRemover.setForeground(new java.awt.Color(255, 255, 255));
        JBRemover.setText("Remover");
        JBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(JBRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 120, 50));

        jTEmail.setBackground(new java.awt.Color(51, 51, 51));
        jTEmail.setForeground(new java.awt.Color(255, 255, 255));
        jTEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.add(jTEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 200, -1));

        JBAtualizar.setBackground(new java.awt.Color(51, 102, 255));
        JBAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        JBAtualizar.setText("Atualizar");
        JBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAtualizarActionPerformed(evt);
            }
        });
        jPanel3.add(JBAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 120, 50));

        JBAdicionar.setBackground(new java.awt.Color(51, 102, 255));
        JBAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        JBAdicionar.setText("Adicionar");
        JBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAdicionarActionPerformed(evt);
            }
        });
        jPanel3.add(JBAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 50));

        jCGenero.setBackground(new java.awt.Color(51, 51, 51));
        jCGenero.setForeground(new java.awt.Color(255, 255, 255));
        jCGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outros" }));
        jCGenero.setBorder(null);
        jCGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCGeneroActionPerformed(evt);
            }
        });
        jPanel3.add(jCGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jTNome.setBackground(new java.awt.Color(51, 51, 51));
        jTNome.setForeground(new java.awt.Color(255, 255, 255));
        jTNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTNome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeActionPerformed(evt);
            }
        });
        jPanel3.add(jTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 40));

        jTConfirmarSenha.setBackground(new java.awt.Color(51, 51, 51));
        jTConfirmarSenha.setForeground(new java.awt.Color(255, 255, 255));
        jTConfirmarSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTConfirmarSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirmar senha:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.add(jTConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 200, 40));

        jTSenha.setBackground(new java.awt.Color(51, 51, 51));
        jTSenha.setForeground(new java.awt.Color(255, 255, 255));
        jTSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Senha:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.add(jTSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 40));

        jTCpf.setBackground(new java.awt.Color(51, 51, 51));
        jTCpf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cpf:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTCpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jTCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTCpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTCpf.setToolTipText("");
        jPanel3.add(jTCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        jTDataNascimento.setBackground(new java.awt.Color(51, 51, 51));
        jTDataNascimento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data de nascimento:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jTDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTDataNascimento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTDataNascimento.setToolTipText("");
        jPanel3.add(jTDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel11.setText("Dados do cliente");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel12.setText("Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(366, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here:
        if(jTClientes.getSelectedRow() != -1){

            DefaultTableModel modelo = (DefaultTableModel) jTClientes.getModel();
            modelo.removeRow(jTClientes.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir!");
        }
    }//GEN-LAST:event_LimparActionPerformed

    private void JTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnomeActionPerformed

    private void jTClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseClicked
        // TODO add your handling code here:
        jCGenero.setSelectedItem(jTClientes.getValueAt(jTClientes.getSelectedRow(), 0).toString());
        jTNome.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 1).toString());
        jTEmail.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 2).toString());
        jTTelefone.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_jTClientesMouseClicked

    private void JCgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCgeneroActionPerformed

    private void JCtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCtipoActionPerformed

    private void jTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeActionPerformed

    private void jCGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCGeneroActionPerformed

    private void JBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAdicionarActionPerformed
        if(jTSenha.getText().equals(jTConfirmarSenha.getText())){
            //Intância a classe FuncionarioDTO de DTO
            ClienteDTO clienteDTO = new ClienteDTO();

            //Seta os dados fornecidos para o FuncionarioDTO
            clienteDTO.setNome(jTNome.getText());
            clienteDTO.setCpf_Cliente(jTCpf.getText());
            clienteDTO.setData_nascimento(jTDataNascimento.getText());
            clienteDTO.setTelefone_Cliente(jTTelefone.getText());
            clienteDTO.setGeneroCliente(jCGenero.getSelectedItem().toString().toUpperCase());
            clienteDTO.setEmail(jTEmail.getText());
            clienteDTO.setPassword_Cliente(jTConfirmarSenha.getText());

            //Instância a classe ConexaoCi
            HttpConnection httpConnection = new HttpConnection();

            //Executa o insert dos dados setados na classe funcionarioDTO ao banco de dados através do funcionarioDAO
            clienteDTO = httpConnection.CadastrarCliente(clienteDTO);

            //Verifica se o cadastro foi efetuado com sucesso.
            if(clienteDTO != null){
                carregarClientes();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "ERRO: As senhas devem ser iguais.");
        }         
    }//GEN-LAST:event_JBAdicionarActionPerformed

    private void JBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAtualizarActionPerformed
        if(jTClientes.getSelectedRow() != -1){
            jTClientes.setValueAt(jCGenero.getSelectedItem(), jTClientes.getSelectedRow(), 0);
            jTClientes.setValueAt(jTNome.getText(), jTClientes.getSelectedRow(), 1);
            jTClientes.setValueAt(jTEmail.getText(), jTClientes.getSelectedRow(),2);
            jTClientes.setValueAt(jTTelefone.getText(), jTClientes.getSelectedRow(), 3);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para atualizar");
        }
    }//GEN-LAST:event_JBAtualizarActionPerformed

    private void JBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRemoverActionPerformed

        if(jTClientes.getSelectedRow() != -1){

            DefaultTableModel modelop = (DefaultTableModel) jTClientes.getModel();
            modelop.removeRow(jTClientes.getSelectedRow());

        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir!");
        }

    }//GEN-LAST:event_JBRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAdicionar;
    private javax.swing.JButton JBAtualizar;
    private javax.swing.JButton JBRemover;
    private javax.swing.JMenuItem Limpar;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jCGenero;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClientes;
    private javax.swing.JPasswordField jTConfirmarSenha;
    private javax.swing.JFormattedTextField jTCpf;
    private javax.swing.JFormattedTextField jTDataNascimento;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTNome;
    private javax.swing.JPasswordField jTSenha;
    private javax.swing.JFormattedTextField jTTelefone;
    // End of variables declaration//GEN-END:variables
}
