package View;

import Utils.FuncionarioDTO;
import View.Login;
import View.Clientes;
import View.DashboardFuncionario;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno.Tarde
 */
public class DashboardFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtendenteNova
     */
    
    public void ExibirDados(FuncionarioDTO funcionarioDTO){
        jLNome.setText(funcionarioDTO.getNome_funcionario() + "!");
    }
    
    public DashboardFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardFuncionario = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLFuncionariosAtivos2 = new javax.swing.JLabel();
        jLVisualizarFuncionarios2 = new javax.swing.JLabel();
        jLGrafico = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLFuncionariosAtivos1 = new javax.swing.JLabel();
        jLVisualizarFuncionarios1 = new javax.swing.JLabel();
        jLGrafico1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLFuncionariosAtivos = new javax.swing.JLabel();
        jLVisualizarFuncionarios = new javax.swing.JLabel();
        jLGrafico2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jBClientes = new javax.swing.JButton();
        jBLogout = new javax.swing.JButton();
        jBAdocoes = new javax.swing.JButton();
        jBDenuncias = new javax.swing.JButton();
        jBDoacoes = new javax.swing.JButton();
        jBAnimais = new javax.swing.JButton();
        jBConsultas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLFundo = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(24, 24, 24));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clientes cadastrados");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 20));

        jLFuncionariosAtivos2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLFuncionariosAtivos2.setForeground(new java.awt.Color(255, 255, 255));
        jLFuncionariosAtivos2.setText("632623532");
        jPanel5.add(jLFuncionariosAtivos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 20));

        jLVisualizarFuncionarios2.setForeground(new java.awt.Color(255, 255, 255));
        jLVisualizarFuncionarios2.setText("Visualizar");
        jPanel5.add(jLVisualizarFuncionarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        jLGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GraficoIcon.png"))); // NOI18N
        jPanel5.add(jLGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 56, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 300, 160));

        jPanel4.setBackground(new java.awt.Color(24, 24, 24));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Funcionários cadastrados");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 190, 20));

        jLFuncionariosAtivos1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLFuncionariosAtivos1.setForeground(new java.awt.Color(255, 255, 255));
        jLFuncionariosAtivos1.setText("632623532");
        jPanel4.add(jLFuncionariosAtivos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 20));

        jLVisualizarFuncionarios1.setForeground(new java.awt.Color(255, 255, 255));
        jLVisualizarFuncionarios1.setText("Visualizar");
        jPanel4.add(jLVisualizarFuncionarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, 20));

        jLGrafico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GraficoIcon.png"))); // NOI18N
        jPanel4.add(jLGrafico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 56, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 300, 160));

        jPanel3.setBackground(new java.awt.Color(24, 24, 24));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Funcionários ativos");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 20));

        jLFuncionariosAtivos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLFuncionariosAtivos.setForeground(new java.awt.Color(255, 255, 255));
        jLFuncionariosAtivos.setText("632623532");
        jPanel3.add(jLFuncionariosAtivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 20));

        jLVisualizarFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        jLVisualizarFuncionarios.setText("Visualizar");
        jPanel3.add(jLVisualizarFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, 20));

        jLGrafico2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GraficoIcon.png"))); // NOI18N
        jPanel3.add(jLGrafico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 56, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 300, 160));

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/PetTopiaLogo.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 130));

        jBClientes.setBackground(new java.awt.Color(24, 24, 24));
        jBClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBClientes.setForeground(new java.awt.Color(255, 255, 255));
        jBClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/PessoasIcon.png"))); // NOI18N
        jBClientes.setText("Clientes");
        jBClientes.setBorder(null);
        jBClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBClientesMouseExited(evt);
            }
        });
        jBClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClientesActionPerformed(evt);
            }
        });
        jPanel2.add(jBClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 340, 320, 50));

        jBLogout.setBackground(new java.awt.Color(24, 24, 24));
        jBLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBLogout.setForeground(new java.awt.Color(255, 255, 255));
        jBLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SairIcon.png"))); // NOI18N
        jBLogout.setText("Logout");
        jBLogout.setBorder(null);
        jBLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLogoutMouseExited(evt);
            }
        });
        jBLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(jBLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 650, 330, 50));

        jBAdocoes.setBackground(new java.awt.Color(24, 24, 24));
        jBAdocoes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBAdocoes.setForeground(new java.awt.Color(255, 255, 255));
        jBAdocoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdocaoIcon.png"))); // NOI18N
        jBAdocoes.setText("Adoções");
        jBAdocoes.setBorder(null);
        jBAdocoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBAdocoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAdocoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAdocoesMouseExited(evt);
            }
        });
        jBAdocoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdocoesActionPerformed(evt);
            }
        });
        jPanel2.add(jBAdocoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 550, 320, 50));

        jBDenuncias.setBackground(new java.awt.Color(24, 24, 24));
        jBDenuncias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBDenuncias.setForeground(new java.awt.Color(255, 255, 255));
        jBDenuncias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/MegafoneIcon.png"))); // NOI18N
        jBDenuncias.setText("Denúncias");
        jBDenuncias.setBorder(null);
        jBDenuncias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBDenuncias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBDenunciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBDenunciasMouseExited(evt);
            }
        });
        jBDenuncias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDenunciasActionPerformed(evt);
            }
        });
        jPanel2.add(jBDenuncias, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 200, 300, 50));

        jBDoacoes.setBackground(new java.awt.Color(24, 24, 24));
        jBDoacoes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBDoacoes.setForeground(new java.awt.Color(255, 255, 255));
        jBDoacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DoacaoIcon.png"))); // NOI18N
        jBDoacoes.setText("Doações");
        jBDoacoes.setBorder(null);
        jBDoacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBDoacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBDoacoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBDoacoesMouseExited(evt);
            }
        });
        jBDoacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDoacoesActionPerformed(evt);
            }
        });
        jPanel2.add(jBDoacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 480, 320, 50));

        jBAnimais.setBackground(new java.awt.Color(24, 24, 24));
        jBAnimais.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBAnimais.setForeground(new java.awt.Color(255, 255, 255));
        jBAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/PataIcon.png"))); // NOI18N
        jBAnimais.setText("Animais");
        jBAnimais.setBorder(null);
        jBAnimais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBAnimais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAnimaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAnimaisMouseExited(evt);
            }
        });
        jBAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnimaisActionPerformed(evt);
            }
        });
        jPanel2.add(jBAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 410, 320, 50));

        jBConsultas.setBackground(new java.awt.Color(24, 24, 24));
        jBConsultas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jBConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/TabelaIcon.png"))); // NOI18N
        jBConsultas.setText("Consultas");
        jBConsultas.setBorder(null);
        jBConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBConsultasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBConsultasMouseExited(evt);
            }
        });
        jBConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultasActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 270, 300, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 770));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Seja bem-vindo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 120, 20));

        jLFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FundoDashboard.png"))); // NOI18N
        jPanel1.add(jLFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        jLNome.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLNome.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jLNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 660, 40));

        DashboardFuncionario.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DashboardFuncionarioLayout = new javax.swing.GroupLayout(DashboardFuncionario);
        DashboardFuncionario.setLayout(DashboardFuncionarioLayout);
        DashboardFuncionarioLayout.setHorizontalGroup(
            DashboardFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DashboardFuncionarioLayout.setVerticalGroup(
            DashboardFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardFuncionario)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardFuncionario)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultasActionPerformed
        // TODO add your handling code here:
        Consultas consultas = new Consultas();
        DashboardFuncionario.add(consultas);
        consultas.setVisible(true);
        consultas.setBounds(247, -30, 1035, 1000);
    }//GEN-LAST:event_jBConsultasActionPerformed

    private void jBConsultasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConsultasMouseExited
        // TODO add your handling code here:
        jBConsultas.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBConsultasMouseExited

    private void jBConsultasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConsultasMouseEntered
        // TODO add your handling code here:
        jBConsultas.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBConsultasMouseEntered

    private void jBAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnimaisActionPerformed
        // TODO add your handling code here:
        Animais animais = new Animais();
        DashboardFuncionario.add(animais);
        animais.setVisible(true);
        animais.setBounds(247, -30, 1035, 1000);
    }//GEN-LAST:event_jBAnimaisActionPerformed

    private void jBAnimaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAnimaisMouseExited
        // TODO add your handling code here:
        jBAnimais.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBAnimaisMouseExited

    private void jBAnimaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAnimaisMouseEntered
        // TODO add your handling code here:
        jBAnimais.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBAnimaisMouseEntered

    private void jBDoacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDoacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBDoacoesActionPerformed

    private void jBDoacoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDoacoesMouseExited
        // TODO add your handling code here:
        jBDoacoes.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBDoacoesMouseExited

    private void jBDoacoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDoacoesMouseEntered
        // TODO add your handling code here:
        jBDoacoes.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBDoacoesMouseEntered

    private void jBDenunciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDenunciasActionPerformed
        // TODO add your handling code here:
        EnderecoDenuncia endereco = new EnderecoDenuncia(DashboardFuncionario);  // Passa o WorkspaceFuncionario
        DashboardFuncionario.add(endereco);
        endereco.setVisible(true);
        endereco.setBounds(400, 0, 410, 670);
    }//GEN-LAST:event_jBDenunciasActionPerformed

    private void jBDenunciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDenunciasMouseExited
        // TODO add your handling code here:
        jBDenuncias.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBDenunciasMouseExited

    private void jBDenunciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDenunciasMouseEntered
        // TODO add your handling code here:
        jBDenuncias.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBDenunciasMouseEntered

    private void jBAdocoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdocoesActionPerformed
        // TODO add your handling code here:
        Clientes CadastrarClientes = new Clientes();
        DashboardFuncionario.add(CadastrarClientes);
        CadastrarClientes.setVisible(true);
        CadastrarClientes.setBounds(247, -30, 1035, 1000);
    }//GEN-LAST:event_jBAdocoesActionPerformed

    private void jBAdocoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAdocoesMouseExited
        // TODO add your handling code here:
        jBAdocoes.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBAdocoesMouseExited

    private void jBAdocoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAdocoesMouseEntered
        // TODO add your handling code here:
        jBAdocoes.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBAdocoesMouseEntered

    private void jBLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLogoutActionPerformed
        // TODO add your handling code here:
        int Option = JOptionPane.showConfirmDialog(null,"Você tem Certeza?","Atenção", JOptionPane.YES_NO_OPTION);
        if(Option == JOptionPane.YES_OPTION){
            Login Logout = new Login();
            this.dispose();
            Logout.setVisible(true);
        }
    }//GEN-LAST:event_jBLogoutActionPerformed

    private void jBLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLogoutMouseExited
        // TODO add your handling code here:
        jBLogout.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBLogoutMouseExited

    private void jBLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLogoutMouseEntered
        // TODO add your handling code here:
        jBLogout.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBLogoutMouseEntered

    private void jBClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClientesActionPerformed
        // TODO add your handling code here:
        Clientes clientes = new Clientes();
        DashboardFuncionario.add(clientes);
        clientes.setVisible(true);
        clientes.setBounds(230, -30, 1173, 1024);
    }//GEN-LAST:event_jBClientesActionPerformed

    private void jBClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBClientesMouseExited
        // TODO add your handling code here:
        jBClientes.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBClientesMouseExited

    private void jBClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBClientesMouseEntered
        // TODO add your handling code here:
        jBClientes.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBClientesMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DashboardFuncionario;
    private javax.swing.JButton jBAdocoes;
    private javax.swing.JButton jBAnimais;
    private javax.swing.JButton jBClientes;
    private javax.swing.JButton jBConsultas;
    private javax.swing.JButton jBDenuncias;
    private javax.swing.JButton jBDoacoes;
    private javax.swing.JButton jBLogout;
    private javax.swing.JLabel jLFuncionariosAtivos;
    private javax.swing.JLabel jLFuncionariosAtivos1;
    private javax.swing.JLabel jLFuncionariosAtivos2;
    private javax.swing.JLabel jLFundo;
    private javax.swing.JLabel jLGrafico;
    private javax.swing.JLabel jLGrafico1;
    private javax.swing.JLabel jLGrafico2;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLVisualizarFuncionarios;
    private javax.swing.JLabel jLVisualizarFuncionarios1;
    private javax.swing.JLabel jLVisualizarFuncionarios2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
