package View;


import View.Estoque;
import Utils.ConexaoCi;
import Utils.ConexaoCi;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Utils.DTO;
import Utils.FuncionarioDTO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Oruam
 */
public class Funcionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFuncionarios
     */
    public Funcionarios() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Limpar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTFuncionarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTcpf = new javax.swing.JFormattedTextField();
        JTData = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        JBRemover = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTnome = new javax.swing.JTextField();
        JTemail = new javax.swing.JTextField();
        JTpassword = new javax.swing.JTextField();
        JCgenero = new javax.swing.JComboBox<>();
        JBAtualizar = new javax.swing.JButton();
        JBAdicionar = new javax.swing.JButton();
        JCtipo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jButton6.setText("jButton6");

        Limpar.setText("jMenuItem1");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Limpar);

        setBorder(null);
        setClosable(true);
        setTitle("Funcionários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setInheritsPopupMenu(true);
        setName("Tela Funcionário"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JTFuncionarios.setBackground(new java.awt.Color(246, 242, 242));
        JTFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Função", "nome", "cpf", "Data de Nasc", "genero", "Código"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTFuncionarios);

        jPanel3.setBackground(new java.awt.Color(246, 242, 242));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("cpf:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel5.setText("Data de nascimento:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel7.setText("genero:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        JTcpf.setBackground(new java.awt.Color(51, 51, 51));
        JTcpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            JTcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(JTcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, -1));

        JTData.setBackground(new java.awt.Color(51, 51, 51));
        JTData.setForeground(new java.awt.Color(255, 255, 255));
        try {
            JTData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTDataActionPerformed(evt);
            }
        });
        jPanel3.add(JTData, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, -1));

        jLabel6.setText("Função:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        JBRemover.setBackground(new java.awt.Color(255, 0, 0));
        JBRemover.setForeground(new java.awt.Color(255, 255, 255));
        JBRemover.setText("Remover");
        JBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(JBRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 120, 50));

        jLabel8.setText("Usuário:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel2.setText("nome:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        JTnome.setBackground(new java.awt.Color(51, 51, 51));
        JTnome.setForeground(new java.awt.Color(255, 255, 255));
        JTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTnomeActionPerformed(evt);
            }
        });
        jPanel3.add(JTnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 260, -1));

        JTemail.setBackground(new java.awt.Color(51, 51, 51));
        JTemail.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(JTemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 200, -1));

        JTpassword.setBackground(new java.awt.Color(51, 51, 51));
        JTpassword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(JTpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 200, -1));

        JCgenero.setBackground(new java.awt.Color(246, 242, 242));
        JCgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        JCgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCgeneroActionPerformed(evt);
            }
        });
        jPanel3.add(JCgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        JBAtualizar.setBackground(new java.awt.Color(51, 102, 255));
        JBAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        JBAtualizar.setText("Atualizar");
        JBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAtualizarActionPerformed(evt);
            }
        });
        jPanel3.add(JBAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 120, 50));

        JBAdicionar.setBackground(new java.awt.Color(51, 102, 255));
        JBAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        JBAdicionar.setText("Adicionar");
        JBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAdicionarActionPerformed(evt);
            }
        });
        jPanel3.add(JBAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, 50));

        JCtipo.setBackground(new java.awt.Color(246, 242, 242));
        JCtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atendente", "Administrador", "Gerente" }));
        JCtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCtipoActionPerformed(evt);
            }
        });
        jPanel3.add(JCtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel10.setText("password:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel11.setText("Dados do funcionário");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel12.setText("Funcionários");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAdicionarActionPerformed
        //Intância a classe FuncionarioDTO de DTO
        FuncionarioDTO funcionarioDTO = new FuncionarioDTO();
        
        //Seta os dados fornecidos para o FuncionarioDTO
        funcionarioDTO.setTipo(JCtipo.getSelectedItem().toString());
        funcionarioDTO.setNome(JTnome.getText());       
        funcionarioDTO.setCpf(JTcpf.getText());
        funcionarioDTO.setDataNascimento(JTData.getText());
        funcionarioDTO.setGenero(JCgenero.getSelectedItem().toString());
        funcionarioDTO.setEmail(JTemail.getText());
        funcionarioDTO.setPassword(JTpassword.getText());
        
        //Instância a classe ConexaoCi
        ConexaoCi funcionarioDAO = new ConexaoCi();
        
        //Executa o insert dos dados setados na classe funcionarioDTO ao banco de dados através do funcionarioDAO
        int Resultado = funcionarioDAO.AdicionarFuncionario(funcionarioDTO);

        //Verifica se o cadastro foi efetuado com sucesso.
        if(Resultado != -1){
            //Grava os dados setados na classe funcionarioDTO para a tabela de cadastros através de um vetor
            DefaultTableModel Tabela = (DefaultTableModel) JTFuncionarios.getModel();
            Object[] dados = {funcionarioDTO.getTipo(), funcionarioDTO.getNome(), funcionarioDTO.getCpf(), funcionarioDTO.getDataNascimento(), funcionarioDTO.getGenero(), funcionarioDTO.getidFuncionario()};
            Tabela.addRow(dados);
        }                                             
    }//GEN-LAST:event_JBAdicionarActionPerformed

    private void JBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAtualizarActionPerformed
        if(JTFuncionarios.getSelectedRow() != -1){                       
                JTFuncionarios.setValueAt(JTnome.getText(), JTFuncionarios.getSelectedRow(), 0);
                JTFuncionarios.setValueAt(JTemail.getText(), JTFuncionarios.getSelectedRow(),6);
                JTFuncionarios.setValueAt(JTpassword.getText(), JTFuncionarios.getSelectedRow(), 4);        
                JTFuncionarios.setValueAt(JTcpf.getText(), JTFuncionarios.getSelectedRow(), 2);
                JTFuncionarios.setValueAt(JTData.getText(), JTFuncionarios.getSelectedRow(), 3);
                JTFuncionarios.setValueAt(JCtipo.getSelectedItem(), JTFuncionarios.getSelectedRow(), 1);
                JTFuncionarios.setValueAt(JCgenero.getSelectedItem(), JTFuncionarios.getSelectedRow(),5);           
        }else{
             JOptionPane.showMessageDialog(null, "Selecione uma linha para atualizar");
          }              
    }//GEN-LAST:event_JBAtualizarActionPerformed

    private void JBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRemoverActionPerformed
       
          
    
        
        if(JTFuncionarios.getSelectedRow() != -1){
        
        DefaultTableModel modelop = (DefaultTableModel) JTFuncionarios.getModel();
        modelop.removeRow(JTFuncionarios.getSelectedRow());
       
        
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir!");
        }    
        
        
        
    }//GEN-LAST:event_JBRemoverActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here:
        if(JTFuncionarios.getSelectedRow() != -1){

            DefaultTableModel modelo = (DefaultTableModel) JTFuncionarios.getModel();
            modelo.removeRow(JTFuncionarios.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir!");
        }
    }//GEN-LAST:event_LimparActionPerformed

    private void JTDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTDataActionPerformed

    }//GEN-LAST:event_JTDataActionPerformed

    private void JTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnomeActionPerformed

    private void JTFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFuncionariosMouseClicked
        // TODO add your handling code here:
        JTnome.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 0).toString());
        JTemail.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 1).toString());
        JTpassword.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 2).toString());
        JTcpf.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 3).toString());
        JTData.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 4).toString());
        JCtipo.setSelectedItem(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 5).toString());
        JCgenero.setSelectedItem(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_JTFuncionariosMouseClicked

    private void JCgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCgeneroActionPerformed

    private void JCtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCtipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAdicionar;
    private javax.swing.JButton JBAtualizar;
    private javax.swing.JButton JBRemover;
    private javax.swing.JComboBox<String> JCtipo;
    private javax.swing.JComboBox<String> JCgenero;
    private javax.swing.JFormattedTextField JTcpf;
    private javax.swing.JFormattedTextField JTData;
    private javax.swing.JTable JTFuncionarios;
    private javax.swing.JTextField JTnome;
    private javax.swing.JTextField JTpassword;
    private javax.swing.JTextField JTemail;
    private javax.swing.JMenuItem Limpar;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
